### ISSUE TITLE
UnicodeEncodeError

### ISSUE THREAD

**Issue by wovo** [phseiff/github-flavored-markdown-to-html#50]
I try to run on windows. I get this error, event with an empty input file:

C:\ti-software\cv>c:\python38\python.exe -m gh_md_to_html -o OFFLINE test.md -p cv.pdf
Traceback (most recent call last):
  File "c:\python38\lib\runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\python38\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "c:\python38\lib\site-packages\gh_md_to_html\__main__.py", line 5, in <module>
    cmd_to_main()
  File "c:\python38\lib\site-packages\gh_md_to_html\__init__.py", line 1460, in cmd_to_main
    help_file.write(help_text)
  File "c:\python38\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 11751-11752: character maps to <undefined>

**Comment by phseiff** [comment]
Hello, and thanks for your error report!

I will probably find time to fix this within the next view hours (it should be relatively trivial, assuming the error is caused by what I think it is caused); I'll inform you once the bug is fixed.

**Comment by wovo** [comment]
that is a quick response!


Wouter van Ooijen

0638150444 - HL15 4.060

________________________________

**Comment by phseiff** [comment]
I can't replicate the problem on my own machine, probably due to using a different operating system, but I found two possible ways to fix it, one which is more elegant (though I'm not sure whether it actually works due to being unable to test it), and one that I am entirely sure will work. Both will make no difference to you as a user.

Could you update to version `v1.17.3` (e.g. via `pip3 install --upgrade gh-md-to-html==1.17.3`) and tell me whether it fixes the problem?
In case it doesn't, you can update to `v1.17.4`, which should certainly fix the problem.

**Comment by wovo** [comment]
With 1.17.3 I offline I now get:

C:\ti-software\cv>c:\python38\python.exe -m gh_md_to_html -o OFFLINE readme.md -p cv.pdf
usage: __main__.py [-h] [-t {file,repo,web,string}] [-w WEBSITE_ROOT [WEBSITE_ROOT ...]]
                   [-d DESTINATION [DESTINATION ...]] [-i [IMAGE_PATHS [IMAGE_PATHS ...]]]
                   [-c CSS_PATHS [CSS_PATHS ...]] [-n OUTPUT_NAME [OUTPUT_NAME ...]] [-p OUTPUT_PDF [OUTPUT_PDF ...]]
                   [-m MATH] [-f FOOTER [FOOTER ...]] [-x EXTRA_CSS [EXTRA_CSS ...]] [-s STYLE_PDF]
                   [-o CORE_CONVERTER [CORE_CONVERTER ...]] [-e COMPRESS_IMAGES [COMPRESS_IMAGES ...]] [-a TOC]
                   [--dont-make-images-links DONT_MAKE_IMAGES_LINKS] [--emoji-support EMOJI_SUPPORT]
                   [-b BOX_WIDTH [BOX_WIDTH ...]] [--soft-wrap-in-code-boxes SOFT_WRAP_IN_CODE_BOXES]
                   [--suppress-online-fallbacks SUPPRESS_ONLINE_FALLBACKS]
                   MD-origin [MD-origin ...]
__main__.py: error: the following arguments are required: MD-origin

1.17.3 online still gives the error:

C:\ti-software\cv>c:\python38\python.exe -m gh_md_to_html readme.md -p cv.pdf
Traceback (most recent call last):
  File "c:\python38\lib\runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "c:\python38\lib\runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "c:\python38\lib\runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "c:\python38\lib\site-packages\gh_md_to_html\__init__.py", line 50, in <module>
    HELP = open_local("help.txt", "r").read()
  File "c:\python38\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 11754: character maps to <undefined>

with 1.17.4 the offline version gives the error:

C:\ti-software\cv>c:\python38\python.exe -m gh_md_to_html -o OFFLINE readme.md -p cv.pdf
Traceback (most recent call last):
  File "c:\python38\lib\runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "c:\python38\lib\runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "c:\python38\lib\runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "c:\python38\lib\site-packages\gh_md_to_html\__init__.py", line 50, in <module>
    HELP = open_local("help.txt", "r").read()
  File "c:\python38\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 11754: character maps to <undefined>

the online version first gave a different error:

C:\ti-software\cv>c:\python38\python.exe -m gh_md_to_html readme.md -p cv.pdf
Traceback (most recent call last):
  File "c:\python38\lib\site-packages\gh_md_to_html\__init__.py", line 1471, in cmd_to_main
    result = main(**vars(parser.parse_args()))
  File "c:\python38\lib\site-packages\gh_md_to_html\__init__.py", line 1193, in main
    version_str = str(subprocess.check_output(["wkhtmltopdf", "-V"]), encoding="UTF-8").strip()
  File "c:\python38\lib\subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "c:\python38\lib\subprocess.py", line 489, in run
    with Popen(*popenargs, **kwargs) as process:
  File "c:\python38\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "c:\python38\lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

But when I rerun it now (after running the offline version) I get the error again:

C:\ti-software\cv>c:\python38\python.exe -m gh_md_to_html readme.md -p cv.pdf
Traceback (most recent call last):
  File "c:\python38\lib\runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "c:\python38\lib\runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "c:\python38\lib\runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "c:\python38\lib\site-packages\gh_md_to_html\__init__.py", line 50, in <module>
    HELP = open_local("help.txt", "r").read()
  File "c:\python38\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 11754: character maps to <undefined>

**Comment by phseiff** [comment]
> With 1.17.3 I offline I now get:
> 
> ```
> C:\ti-software\cv>c:\python38\python.exe -m gh_md_to_html -o OFFLINE readme.md -p cv.pdf
> usage: __main__.py [-h] [-t {file,repo,web,string}] [-w WEBSITE_ROOT [WEBSITE_ROOT ...]]
>                    [-d DESTINATION [DESTINATION ...]] [-i [IMAGE_PATHS [IMAGE_PATHS ...]]]
>                    [-c CSS_PATHS [CSS_PATHS ...]] [-n OUTPUT_NAME [OUTPUT_NAME ...]] [-p OUTPUT_PDF [OUTPUT_PDF ...]]
>                    [-m MATH] [-f FOOTER [FOOTER ...]] [-x EXTRA_CSS [EXTRA_CSS ...]] [-s STYLE_PDF]
>                    [-o CORE_CONVERTER [CORE_CONVERTER ...]] [-e COMPRESS_IMAGES [COMPRESS_IMAGES ...]] [-a TOC]
>                    [--dont-make-images-links DONT_MAKE_IMAGES_LINKS] [--emoji-support EMOJI_SUPPORT]
>                    [-b BOX_WIDTH [BOX_WIDTH ...]] [--soft-wrap-in-code-boxes SOFT_WRAP_IN_CODE_BOXES]
>                    [--suppress-online-fallbacks SUPPRESS_ONLINE_FALLBACKS]
>                    MD-origin [MD-origin ...]
> __main__.py: error: the following arguments are required: MD-origin
> ```

You need to specify the positional arguments before the optional ones, like this: `C:\ti-software\cv>c:\python38\python.exe -m gh_md_to_html readme.md -o OFFLINE -p cv.pdf`

> 1.17.3 online still gives the error:
> 
> ```
> C:\ti-software\cv>c:\python38\python.exe -m gh_md_to_html readme.md -p cv.pdf
> Traceback (most recent call last):
>   File "c:\python38\lib\runpy.py", line 183, in _run_module_as_main
>     mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
>   File "c:\python38\lib\runpy.py", line 142, in _get_module_details
>     return _get_module_details(pkg_main_name, error)
>   File "c:\python38\lib\runpy.py", line 109, in _get_module_details
>     __import__(pkg_name)
>   File "c:\python38\lib\site-packages\gh_md_to_html\__init__.py", line 50, in <module>
>     HELP = open_local("help.txt", "r").read()
>   File "c:\python38\lib\encodings\cp1252.py", line 23, in decode
>     return codecs.charmap_decode(input,self.errors,decoding_table)[0]
> UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 11754: character maps to <undefined>
> ```

It seems likely to me that this error always occurs when you run the tool for the second time in a row after installing it, no matter whether you use the online or offline version.

> with 1.17.4 the offline version gives the error:
> 
> ```
> C:\ti-software\cv>c:\python38\python.exe -m gh_md_to_html -o OFFLINE readme.md -p cv.pdf
> Traceback (most recent call last):
>   File "c:\python38\lib\runpy.py", line 183, in _run_module_as_main
>     mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
>   File "c:\python38\lib\runpy.py", line 142, in _get_module_details
>     return _get_module_details(pkg_main_name, error)
>   File "c:\python38\lib\runpy.py", line 109, in _get_module_details
>     __import__(pkg_name)
>   File "c:\python38\lib\site-packages\gh_md_to_html\__init__.py", line 50, in <module>
>     HELP = open_local("help.txt", "r").read()
>   File "c:\python38\lib\encodings\cp1252.py", line 23, in decode
>     return codecs.charmap_decode(input,self.errors,decoding_table)[0]
> UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 11754: character maps to <undefined>
> ```

See above.

> the online version first gave a different error:
> 
> ```
> C:\ti-software\cv>c:\python38\python.exe -m gh_md_to_html readme.md -p cv.pdf
> Traceback (most recent call last):
>   File "c:\python38\lib\site-packages\gh_md_to_html\__init__.py", line 1471, in cmd_to_main
>     result = main(**vars(parser.parse_args()))
>   File "c:\python38\lib\site-packages\gh_md_to_html\__init__.py", line 1193, in main
>     version_str = str(subprocess.check_output(["wkhtmltopdf", "-V"]), encoding="UTF-8").strip()
>   File "c:\python38\lib\subprocess.py", line 411, in check_output
>     return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
>   File "c:\python38\lib\subprocess.py", line 489, in run
>     with Popen(*popenargs, **kwargs) as process:
>   File "c:\python38\lib\subprocess.py", line 854, in __init__
>     self._execute_child(args, executable, preexec_fn, close_fds,
>   File "c:\python38\lib\subprocess.py", line 1307, in _execute_child
>     hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
> FileNotFoundError: [WinError 2] The system cannot find the file specified
> ```

Are you sure you have `wkhtmltopdf` installed like the documentation sais?

> But when I rerun it now (after running the offline version) I get the error again:
> 
> ```
> C:\ti-software\cv>c:\python38\python.exe -m gh_md_to_html readme.md -p cv.pdf
> Traceback (most recent call last):
>   File "c:\python38\lib\runpy.py", line 183, in _run_module_as_main
>     mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
>   File "c:\python38\lib\runpy.py", line 142, in _get_module_details
>     return _get_module_details(pkg_main_name, error)
>   File "c:\python38\lib\runpy.py", line 109, in _get_module_details
>     __import__(pkg_name)
>   File "c:\python38\lib\site-packages\gh_md_to_html\__init__.py", line 50, in <module>
>     HELP = open_local("help.txt", "r").read()
>   File "c:\python38\lib\encodings\cp1252.py", line 23, in decode
>     return codecs.charmap_decode(input,self.errors,decoding_table)[0]
> UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 11754: character maps to <undefined>
> ```

Probably the thing I mentioned above.

---

It seems to me that 1.17.3 and 1.17.4 seem to have the same underlying issues, so I based 1.17.5 on 1.17.3.
Would you mind updating and re-checking again, this time with the arguments in the specified order? The error regarding `wkhtmltopdf` remains, though, since I suspect it is because of missing dependencies (could you verify whether you have `wkhtmltopdf` installed?)

You might encounter even more UnicodeEncodeErrors after this update. If this is the case, I can fix them, but I want to see whether there are any first so I don't add additional clutter to fix a problem that doesn't exist.

**Comment by wovo** [comment]
After updating to 1.17.5 I got

C:\ti-software\cv>c:\python38\python.exe -m gh_md_to_html readme.md -o OFFLINE -p cv.pdf
Traceback (most recent call last):
  File "c:\python38\lib\site-packages\gh_md_to_html\__init__.py", line 1471, in cmd_to_main
    result = main(**vars(parser.parse_args()))
  File "c:\python38\lib\site-packages\gh_md_to_html\__init__.py", line 1193, in main
    version_str = str(subprocess.check_output(["wkhtmltopdf", "-V"]), encoding="UTF-8").strip()
  File "c:\python38\lib\subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "c:\python38\lib\subprocess.py", line 489, in run
    with Popen(*popenargs, **kwargs) as process:
  File "c:\python38\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "c:\python38\lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

wkhtmltopdf was installed, but it did not add itself to the PATH. After 
set PATH=%PATH%;c:/program files/wkhtmltopdf/bin

I finally got

C:\ti-software\cv>c:\python38\python.exe -m gh_md_to_html readme.md -o OFFLINE -p cv.pdf

C:\ti-software\cv>

So, that works! Two problems with the pdf: an image was not included, and the single-pixel-border tables were now all double-bordered. But: it is a multi-page pdf, which I didn't get with some other conversion I tried.

But the online version still errors:

C:\ti-software\cv>c:\python38\python.exe -m gh_md_to_html readme.md -p cv.pdf
Traceback (most recent call last):
  File "c:\python38\lib\runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\python38\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "c:\python38\lib\site-packages\gh_md_to_html\__main__.py", line 5, in <module>
    cmd_to_main()
  File "c:\python38\lib\site-packages\gh_md_to_html\__init__.py", line 1471, in cmd_to_main
    result = main(**vars(parser.parse_args()))
  File "c:\python38\lib\site-packages\gh_md_to_html\__init__.py", line 1219, in main
    pdfkit.from_file(
  File "c:\python38\lib\site-packages\pdfkit\api.py", line 49, in from_file
    return r.to_pdf(output_path)
  File "c:\python38\lib\site-packages\pdfkit\pdfkit.py", line 159, in to_pdf
    raise IOError("wkhtmltopdf exited with non-zero code {0}. error:\n{1}".format(exit_code, stderr))
OSError: wkhtmltopdf exited with non-zero code 1. error:
QPainter::begin(): Returned false
Exit with code 1, due to unknown error.

PS the md I use it at github.com/wovo/cv

**Comment by phseiff** [comment]
> wkhtmltopdf was installed, but it did not add itself to the PATH. After
> set `PATH=%PATH%;c:/program files/wkhtmltopdf/bin` [i finally got it to work]

Glad to hear that, I added a note to the README that you have to add `wkhtmltopdf` to the PATH on Windows.

> an image was not included, and the single-pixel-border tables were now all double-bordered.

Looking into this right now.

> But the online version still errors:

That's weird; also looking into this right now.

> PS the md I use it at github.com/wovo/cv

Thanks, that's certainly going to help with debugging!

**Comment by phseiff** [comment]
> So, that works! Two problems with the pdf: an image was not included, and the single-pixel-border tables were now all double-bordered.
> But the online version still errors:

The issue with the double border was actually already resolved in a much older version, now that I think about it, so I'm surprised this is happening to you. On my system, I can replicate neither the error with the online version, nor the missing image, nor the error in the online version.

Some reasons why this might be occurring for you:
* Are you sure the missing image and double borders are in the resulting PDF file, or do they only occur in the generated HTML file? In case you tried to open the resulting HTML file in the browser (e.g. by double-clicking it) and expected it to show the image and use GitHub's README stylesheet, you should have added the `-w .` option. The reason for this is that `gh-md-to-html` (by default) uses absolute relative links for embedding CSS and images, based on the assumption that you want to host the generated HTML file at the root of a website. If you want to be able to view the HTML file in the browser on your local machine (with `file://`), you need to supply the `-w .` option.
  This shouldn't affect the resulting PDF file regardless, though.
* Are you sure you are using the latest version of `wkhtmltopdf` (version 0.12.6), to which [the README links](https://wkhtmltopdf.org/downloads.html)? Older versions can have issues with images and style sheets, which is also why the README specifically links to the newer version, though I admit I should have made it clearer that there are explicit version requirements for `wkhtmltopdf` in the README.

Here is the PDF I get with both commands you used:

[cv.pdf](https://github.com/phseiff/github-flavored-markdown-to-html/files/6877995/cv.pdf)

Would you mind sharing your own result for comparison? You can drag-and-drop it into GitHub's text box to attach it to your reply.

**Comment by wovo** [comment]
C:\ti-software\cv>wkhtmltopdf -v
Unknown switch -v
Name:
  wkhtmltopdf 0.12.6 (with patched qt)

FYI if the pdf is still open, I get:

C:\ti-software\cv>c:\python38\python.exe -m gh_md_to_html readme.md -p cv.pdf
Traceback (most recent call last):
  File "c:\python38\lib\runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\python38\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "c:\python38\lib\site-packages\gh_md_to_html\__main__.py", line 5, in <module>
    cmd_to_main()
  File "c:\python38\lib\site-packages\gh_md_to_html\__init__.py", line 1471, in cmd_to_main
    result = main(**vars(parser.parse_args()))
  File "c:\python38\lib\site-packages\gh_md_to_html\__init__.py", line 1219, in main
    pdfkit.from_file(
  File "c:\python38\lib\site-packages\pdfkit\api.py", line 49, in from_file
    return r.to_pdf(output_path)
  File "c:\python38\lib\site-packages\pdfkit\pdfkit.py", line 159, in to_pdf
    raise IOError("wkhtmltopdf exited with non-zero code {0}. error:\n{1}".format(exit_code, stderr))
OSError: wkhtmltopdf exited with non-zero code 1. error:
QPainter::begin(): Returned false
Exit with code 1, due to unknown error.

using -w . both the offline and the online version gives the correct html (single bordered tables, with image) but the wrong pdf (double bordered tables, no image).

[readme.zip](https://github.com/phseiff/github-flavored-markdown-to-html/files/6878161/readme.zip)

**Comment by phseiff** [comment]
> C:\ti-software\cv>wkhtmltopdf -v
> Unknown switch -v
> Name:
> wkhtmltopdf 0.12.6 (with patched qt)

Thanks, that seems right so far!

> FYI if the pdf is still open, I get:
> 
> ```
> C:\ti-software\cv>c:\python38\python.exe -m gh_md_to_html readme.md -p cv.pdf
> Traceback (most recent call last):
> File "c:\python38\lib\runpy.py", line 192, in _run_module_as_main return _run_code(code, main_globals, None, File "c:\python38\lib\runpy.py", line 85, in _run_code exec(code, run_globals) File "c:\python38\lib\site-packages\gh_md_to_html__main__.py", line 5, in cmd_to_main() File "c:\python38\lib\site-packages\gh_md_to_html__init__.py", line 1471, in cmd_to_main result = main(**vars(parser.parse_args())) File "c:\python38\lib\site-packages\gh_md_to_html__init__.py", line 1219, in main
> pdfkit.from_file(
> File "c:\python38\lib\site-packages\pdfkit\api.py", line 49, in from_file
> return r.to_pdf(output_path)
> File "c:\python38\lib\site-packages\pdfkit\pdfkit.py", line 159, in to_pdf
> raise IOError("wkhtmltopdf exited with non-zero code {0}. error:\n{1}".format(exit_code, stderr))
> OSError: wkhtmltopdf exited with non-zero code 1. error:
> QPainter::begin(): Returned false
> Exit with code 1, due to unknown error.
> ```

I assume that with "still open", you mean that it is opened in the PDF viewer, right? Because that's probably because the PDF viewer locks the file as long as it is opened and blocks write access in the process, leading to a failed write (this seems to be the case with [Acrobat Reader](https://superuser.com/questions/599442/pdf-viewer-that-handles-live-updating-of-pdf-doesnt-lock-the-file), for example). There's nothing `gh-md-to-html`can change about that, though, because there is no way to prevent or circumvent other programs from blocking write access to a file.

It's useful to know nonetheless, though, since I could add a more helpful error message for that. Thanks!

> using -w . both the offline and the online version gives the correct html (single bordered tables, with image) but the wrong pdf (double bordered tables, no image).
> 
> [readme.zip](https://github.com/phseiff/github-flavored-markdown-to-html/files/6878161/readme.zip)

I'm currently looking into this (can't replicate it, though; probably has to do with the different file paths that Windows and Linux use).
Thanks for sharing the files!

**Comment by rever96** [comment]
I have the same error:

```
python -m gh_md_to_html .\documentazione_v3wEewko.md -o OFFLINE -p test.pdf
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\rever\AppData\Roaming\Python\Python310\site-packages\gh_md_to_html\__main__.py", line 5, in <module>
    cmd_to_main()
  File "C:\Users\rever\AppData\Roaming\Python\Python310\site-packages\gh_md_to_html\__init__.py", line 1618, in cmd_to_main
    result = main(**vars(parser.parse_args()))
  File "C:\Users\rever\AppData\Roaming\Python\Python310\site-packages\gh_md_to_html\__init__.py", line 775, in main
    md_content = f.read()
  File "C:\Program Files\Python310\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 2014: character maps to <undefined>
```

I'm on windows.

wkhtmltopdf path is correctly setted

```
wkhtmltopdf --version
wkhtmltopdf 0.12.6 (with patched qt)
```
